// The full ABC Public School demo roster, used only by prisma/seed.js to
// populate the real `Student` table (see lib/students.js, migrated off
// in-memory storage). Kept as its own dependency-free module — rather than
// living inside lib/students.js like before — so prisma/seed.js (a plain
// CommonJS script run via `node`, not through Next's bundler) can load it
// with a dynamic `import()` without pulling in lib/school.js or
// lib/schoolScope.js, neither of which this seed data needs.
//
const SEED_STUDENTS = [
  {
    admissionId: 'ADM-2026-1042',
    firstName: 'Aarav',
    lastName: 'Sharma',
    initials: 'AS',
    class: 'Class 8',
    section: 'A',
    academicSession: '2026-27',
    admissionDate: '2026-04-02',
    dob: '2013-07-14',
    gender: 'Male',
    bloodGroup: 'B+',
    nationality: 'India',
    aadhaarNumber: '2345 6789 0121',
    aadhaarDocumentName: 'aarav-sharma-aadhaar.pdf',
    whatsappNumber: '+91 98765 43210',
    status: 'Active',
    previousSchool: { name: 'Little Angels School', board: 'CBSE', lastClassPercentage: '89%' },
    emergencyContacts: {
      primary: { name: 'Rajesh Sharma', relationship: 'Father', phone: '+91 98765 43210' },
      secondary: { name: 'Priya Sharma', relationship: 'Mother', phone: '+91 98765 43211' },
      trustedRelativePhone: '+91 98765 00011',
    },
    feeDetails: {
      admissionFeePaidDate: '2026-04-02',
      admissionFeeAmount: '15000',
      structureType: 'Annual',
      structureAmount: '85000',
      paymentStatus: 'Paid',
      outstandingDues: '0',
    },
    guardian: {
      relationship: 'Father',
      fullName: 'Rajesh Sharma',
      phone: '+91 98765 43210',
      email: 'rajesh.sharma@example.com',
      occupation: 'Software Engineer',
      aadhaarNumber: '8901 2345 6781',
      aadhaarDocumentName: 'rajesh-sharma-aadhaar.pdf',
    },
    secondaryGuardian: {
      relationship: 'Mother',
      fullName: 'Priya Sharma',
      phone: '+91 98765 43211',
      email: 'priya.sharma@example.com',
      occupation: 'Teacher',
      aadhaarNumber: '9012 3456 7892',
      aadhaarDocumentName: 'priya-sharma-guardian-aadhaar.pdf',
    },
    address: {
      line1: '221B, Green Park Colony',
      line2: 'Near City Mall',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      pinCode: '226001',
    },
  },
  {
    admissionId: 'ADM-2026-1043',
    firstName: 'Ananya',
    lastName: 'Singh',
    initials: 'AS',
    class: 'Class 7',
    section: 'B',
    academicSession: '2026-27',
    admissionDate: '2026-04-03',
    dob: '2014-02-21',
    gender: 'Female',
    bloodGroup: 'O+',
    nationality: 'India',
    aadhaarNumber: '3456 7890 1232',
    aadhaarDocumentName: 'ananya-singh-aadhaar.pdf',
    whatsappNumber: '+91 91234 56780',
    status: 'Active',
    previousSchool: { name: 'Sunrise Public School', board: 'ICSE', lastClassPercentage: '92%' },
    emergencyContacts: {
      primary: { name: 'Amit Singh', relationship: 'Father', phone: '+91 91234 56780' },
      secondary: { name: '', relationship: '', phone: '' },
      trustedRelativePhone: '+91 91234 00022',
    },
    feeDetails: {
      admissionFeePaidDate: '2026-04-03',
      admissionFeeAmount: '12000',
      structureType: 'Monthly',
      structureAmount: '6500',
      paymentStatus: 'Pending',
      outstandingDues: '6500',
    },
    guardian: {
      relationship: 'Father',
      fullName: 'Amit Singh',
      phone: '+91 91234 56780',
      email: 'amit.singh@example.com',
      occupation: 'Business Owner',
      aadhaarNumber: '1234 5678 9013',
      aadhaarDocumentName: 'amit-singh-aadhaar.pdf',
    },
    address: {
      line1: '48, Sector 12',
      line2: '',
      city: 'Noida',
      state: 'Uttar Pradesh',
      pinCode: '201301',
    },
  },
  {
    admissionId: 'ADM-2026-1044',
    firstName: 'Kabir',
    lastName: 'Verma',
    initials: 'KV',
    class: 'Class 8',
    section: 'A',
    academicSession: '2026-27',
    admissionDate: '2026-04-04',
    dob: '2013-11-05',
    gender: 'Male',
    bloodGroup: 'A+',
    nationality: 'India',
    aadhaarNumber: '4567 8901 2343',
    aadhaarDocumentName: 'kabir-verma-aadhaar.pdf',
    whatsappNumber: '+91 99887 76655',
    status: 'Active',
    previousSchool: { name: 'Green Valley School', board: 'CBSE', lastClassPercentage: '85%' },
    emergencyContacts: {
      primary: { name: 'Sunita Verma', relationship: 'Mother', phone: '+91 99887 76655' },
      secondary: { name: '', relationship: '', phone: '' },
      trustedRelativePhone: '+91 99887 00033',
    },
    feeDetails: {
      admissionFeePaidDate: '2026-04-04',
      admissionFeeAmount: '15000',
      structureType: 'Annual',
      structureAmount: '85000',
      paymentStatus: 'Partial',
      outstandingDues: '20000',
    },
    guardian: {
      relationship: 'Mother',
      fullName: 'Sunita Verma',
      phone: '+91 99887 76655',
      email: 'sunita.verma@example.com',
      occupation: 'Doctor',
      aadhaarNumber: '2345 6789 0124',
      aadhaarDocumentName: 'sunita-verma-aadhaar.pdf',
    },
    address: {
      line1: '15, MG Road',
      line2: '',
      city: 'Kanpur',
      state: 'Uttar Pradesh',
      pinCode: '208001',
    },
  },
  {
    admissionId: 'ADM-2026-1045',
    firstName: 'Ishita',
    lastName: 'Gupta',
    initials: 'IG',
    class: 'Class 6',
    section: 'C',
    academicSession: '2026-27',
    admissionDate: '2026-04-05',
    dob: '2015-03-30',
    gender: 'Female',
    bloodGroup: 'AB+',
    nationality: 'India',
    aadhaarNumber: '5678 9012 3454',
    aadhaarDocumentName: 'ishita-gupta-aadhaar.pdf',
    whatsappNumber: '+91 90000 11223',
    status: 'Active',
    previousSchool: { name: 'St. Mary Convent School', board: 'ICSE', lastClassPercentage: '90%' },
    emergencyContacts: {
      primary: { name: 'Manoj Gupta', relationship: 'Father', phone: '+91 90000 11223' },
      secondary: { name: '', relationship: '', phone: '' },
      trustedRelativePhone: '+91 90000 00044',
    },
    feeDetails: {
      admissionFeePaidDate: '2026-04-05',
      admissionFeeAmount: '10000',
      structureType: 'Monthly',
      structureAmount: '5000',
      paymentStatus: 'Paid',
      outstandingDues: '0',
    },
    guardian: {
      relationship: 'Father',
      fullName: 'Manoj Gupta',
      phone: '+91 90000 11223',
      email: 'manoj.gupta@example.com',
      occupation: 'Accountant',
      aadhaarNumber: '3456 7890 1235',
      aadhaarDocumentName: 'manoj-gupta-aadhaar.pdf',
    },
    address: {
      line1: '9, Civil Lines',
      line2: '',
      city: 'Agra',
      state: 'Uttar Pradesh',
      pinCode: '282002',
    },
  },
  {
    admissionId: 'ADM-2026-1046',
    firstName: 'Vivaan',
    lastName: 'Mehta',
    initials: 'VM',
    class: 'Class 5',
    section: 'A',
    academicSession: '2026-27',
    admissionDate: '2026-04-06',
    dob: '2016-06-18',
    gender: 'Male',
    bloodGroup: 'O-',
    nationality: 'India',
    aadhaarNumber: '6789 0123 4565',
    aadhaarDocumentName: 'vivaan-mehta-aadhaar.pdf',
    whatsappNumber: '+91 98123 45670',
    status: 'Active',
    previousSchool: { name: 'Blue Bells School', board: 'CBSE', lastClassPercentage: '87%' },
    emergencyContacts: {
      primary: { name: 'Deepak Mehta', relationship: 'Father', phone: '+91 98123 45670' },
      secondary: { name: '', relationship: '', phone: '' },
      trustedRelativePhone: '+91 98123 00055',
    },
    feeDetails: {
      admissionFeePaidDate: '2026-04-06',
      admissionFeeAmount: '9000',
      structureType: 'Monthly',
      structureAmount: '4500',
      paymentStatus: 'Overdue',
      outstandingDues: '9000',
    },
    guardian: {
      relationship: 'Father',
      fullName: 'Deepak Mehta',
      phone: '+91 98123 45670',
      email: 'deepak.mehta@example.com',
      occupation: 'Architect',
      aadhaarNumber: '4567 8901 2346',
      aadhaarDocumentName: 'deepak-mehta-guardian-aadhaar.pdf',
    },
    address: {
      line1: '77, Model Town',
      line2: '',
      city: 'Meerut',
      state: 'Uttar Pradesh',
      pinCode: '250001',
    },
  },
  {
    admissionId: 'ADM-2026-1047',
    firstName: 'Diya',
    lastName: 'Kapoor',
    initials: 'DK',
    class: 'Class 4',
    section: 'B',
    academicSession: '2026-27',
    admissionDate: '2026-04-07',
    dob: '2017-09-09',
    gender: 'Female',
    bloodGroup: 'B-',
    nationality: 'India',
    aadhaarNumber: '7890 1234 5676',
    aadhaarDocumentName: 'diya-kapoor-aadhaar.pdf',
    whatsappNumber: '+91 97654 32109',
    status: 'Inactive',
    previousSchool: { name: 'Holy Cross School', board: 'State Board', lastClassPercentage: '76%' },
    emergencyContacts: {
      primary: { name: 'Rekha Kapoor', relationship: 'Grandparent', phone: '+91 97654 32109' },
      secondary: { name: '', relationship: '', phone: '' },
      trustedRelativePhone: '+91 97654 00066',
    },
    feeDetails: {
      admissionFeePaidDate: '2026-04-07',
      admissionFeeAmount: '8000',
      structureType: 'Monthly',
      structureAmount: '4000',
      paymentStatus: 'Overdue',
      outstandingDues: '16000',
    },
    guardian: {
      relationship: 'Guardian',
      fullName: 'Rekha Kapoor',
      phone: '+91 97654 32109',
      email: 'rekha.kapoor@example.com',
      occupation: 'Homemaker',
      aadhaarNumber: '5678 9012 3457',
      aadhaarDocumentName: 'rekha-kapoor-aadhaar.pdf',
    },
    address: {
      line1: '3, Shastri Nagar',
      line2: '',
      city: 'Ghaziabad',
      state: 'Uttar Pradesh',
      pinCode: '201001',
    },
  },
  // Class 8-A / Class 9-A get a fuller real roster (rather than the usual 1-2
  // students per section elsewhere) specifically so the Attendance module has
  // a believable class to mark/report against by default — see the
  // Attendance Module section of SKILL.md for why this section was chosen
  // (it lines up with teacher Rahul Kumar's existing class assignments).
  {
    admissionId: 'ADM-2026-1048',
    firstName: 'Reyansh',
    lastName: 'Joshi',
    initials: 'RJ',
    class: 'Class 8',
    section: 'A',
    academicSession: '2026-27',
    admissionDate: '2026-04-08',
    dob: '2013-05-12',
    gender: 'Male',
    bloodGroup: 'B+',
    nationality: 'India',
    aadhaarNumber: '8901 2345 6787',
    aadhaarDocumentName: 'reyansh-joshi-aadhaar.pdf',
    whatsappNumber: '+91 98111 22334',
    status: 'Active',
    previousSchool: { name: 'Bright Future School', board: 'CBSE', lastClassPercentage: '88%' },
    emergencyContacts: {
      primary: { name: 'Vikram Joshi', relationship: 'Father', phone: '+91 98111 22334' },
      secondary: { name: '', relationship: '', phone: '' },
      trustedRelativePhone: '+91 98111 00077',
    },
    feeDetails: {
      admissionFeePaidDate: '2026-04-08',
      admissionFeeAmount: '15000',
      structureType: 'Annual',
      structureAmount: '85000',
      paymentStatus: 'Paid',
      outstandingDues: '0',
    },
    guardian: {
      relationship: 'Father',
      fullName: 'Vikram Joshi',
      phone: '+91 98111 22334',
      email: 'vikram.joshi@example.com',
      occupation: 'Bank Manager',
      aadhaarNumber: '9012 3456 7898',
      aadhaarDocumentName: 'vikram-joshi-aadhaar.pdf',
    },
    address: { line1: '22, Hazratganj', line2: '', city: 'Lucknow', state: 'Uttar Pradesh', pinCode: '226001' },
  },
  {
    admissionId: 'ADM-2026-1049',
    firstName: 'Saanvi',
    lastName: 'Patel',
    initials: 'SP',
    class: 'Class 8',
    section: 'A',
    academicSession: '2026-27',
    admissionDate: '2026-04-08',
    dob: '2013-08-24',
    gender: 'Female',
    bloodGroup: 'A+',
    nationality: 'India',
    aadhaarNumber: '9012 3456 7889',
    aadhaarDocumentName: 'saanvi-patel-aadhaar.pdf',
    whatsappNumber: '+91 98222 33445',
    status: 'Active',
    previousSchool: { name: 'Sunrise Public School', board: 'CBSE', lastClassPercentage: '91%' },
    emergencyContacts: {
      primary: { name: 'Nisha Patel', relationship: 'Mother', phone: '+91 98222 33445' },
      secondary: { name: '', relationship: '', phone: '' },
      trustedRelativePhone: '+91 98222 00088',
    },
    feeDetails: {
      admissionFeePaidDate: '2026-04-08',
      admissionFeeAmount: '15000',
      structureType: 'Annual',
      structureAmount: '85000',
      paymentStatus: 'Paid',
      outstandingDues: '0',
    },
    guardian: {
      relationship: 'Mother',
      fullName: 'Nisha Patel',
      phone: '+91 98222 33445',
      email: 'nisha.patel@example.com',
      occupation: 'Pharmacist',
      aadhaarNumber: '0123 4567 8909',
      aadhaarDocumentName: 'nisha-patel-aadhaar.pdf',
    },
    address: { line1: '5, Alambagh', line2: '', city: 'Lucknow', state: 'Uttar Pradesh', pinCode: '226005' },
  },
  {
    admissionId: 'ADM-2026-1050',
    firstName: 'Aditya',
    lastName: 'Nair',
    initials: 'AN',
    class: 'Class 8',
    section: 'A',
    academicSession: '2026-27',
    admissionDate: '2026-04-09',
    dob: '2013-01-30',
    gender: 'Male',
    bloodGroup: 'O+',
    nationality: 'India',
    aadhaarNumber: '1123 4567 8901',
    aadhaarDocumentName: 'aditya-nair-aadhaar.pdf',
    whatsappNumber: '+91 98333 44556',
    status: 'Active',
    previousSchool: { name: 'Green Valley School', board: 'ICSE', lastClassPercentage: '84%' },
    emergencyContacts: {
      primary: { name: 'Suresh Nair', relationship: 'Father', phone: '+91 98333 44556' },
      secondary: { name: '', relationship: '', phone: '' },
      trustedRelativePhone: '+91 98333 00099',
    },
    feeDetails: {
      admissionFeePaidDate: '2026-04-09',
      admissionFeeAmount: '15000',
      structureType: 'Monthly',
      structureAmount: '7200',
      paymentStatus: 'Pending',
      outstandingDues: '7200',
    },
    guardian: {
      relationship: 'Father',
      fullName: 'Suresh Nair',
      phone: '+91 98333 44556',
      email: 'suresh.nair@example.com',
      occupation: 'Civil Engineer',
      aadhaarNumber: '1234 5678 9021',
      aadhaarDocumentName: 'suresh-nair-aadhaar.pdf',
    },
    address: { line1: '31, Indira Nagar', line2: '', city: 'Lucknow', state: 'Uttar Pradesh', pinCode: '226016' },
  },
  {
    admissionId: 'ADM-2026-1051',
    firstName: 'Myra',
    lastName: 'Iyer',
    initials: 'MI',
    class: 'Class 8',
    section: 'A',
    academicSession: '2026-27',
    admissionDate: '2026-04-09',
    dob: '2013-10-02',
    gender: 'Female',
    bloodGroup: 'B-',
    nationality: 'India',
    aadhaarNumber: '2234 5678 9012',
    aadhaarDocumentName: 'myra-iyer-aadhaar.pdf',
    whatsappNumber: '+91 98444 55667',
    status: 'Active',
    previousSchool: { name: 'Little Angels School', board: 'CBSE', lastClassPercentage: '93%' },
    emergencyContacts: {
      primary: { name: 'Lakshmi Iyer', relationship: 'Mother', phone: '+91 98444 55667' },
      secondary: { name: '', relationship: '', phone: '' },
      trustedRelativePhone: '+91 98444 00011',
    },
    feeDetails: {
      admissionFeePaidDate: '2026-04-09',
      admissionFeeAmount: '15000',
      structureType: 'Annual',
      structureAmount: '85000',
      paymentStatus: 'Paid',
      outstandingDues: '0',
    },
    guardian: {
      relationship: 'Mother',
      fullName: 'Lakshmi Iyer',
      phone: '+91 98444 55667',
      email: 'lakshmi.iyer@example.com',
      occupation: 'College Professor',
      aadhaarNumber: '2345 6789 0132',
      aadhaarDocumentName: 'lakshmi-iyer-aadhaar.pdf',
    },
    address: { line1: '14, Gomti Nagar', line2: '', city: 'Lucknow', state: 'Uttar Pradesh', pinCode: '226010' },
  },
  {
    admissionId: 'ADM-2026-1052',
    firstName: 'Vihaan',
    lastName: 'Reddy',
    initials: 'VR',
    class: 'Class 8',
    section: 'A',
    academicSession: '2026-27',
    admissionDate: '2026-04-10',
    dob: '2013-03-18',
    gender: 'Male',
    bloodGroup: 'AB+',
    nationality: 'India',
    aadhaarNumber: '3345 6789 0123',
    aadhaarDocumentName: 'vihaan-reddy-aadhaar.pdf',
    whatsappNumber: '+91 98555 66778',
    status: 'Active',
    previousSchool: { name: 'Holy Cross School', board: 'CBSE', lastClassPercentage: '80%' },
    emergencyContacts: {
      primary: { name: 'Kiran Reddy', relationship: 'Father', phone: '+91 98555 66778' },
      secondary: { name: '', relationship: '', phone: '' },
      trustedRelativePhone: '+91 98555 00022',
    },
    feeDetails: {
      admissionFeePaidDate: '2026-04-10',
      admissionFeeAmount: '15000',
      structureType: 'Monthly',
      structureAmount: '7200',
      paymentStatus: 'Overdue',
      outstandingDues: '14400',
    },
    guardian: {
      relationship: 'Father',
      fullName: 'Kiran Reddy',
      phone: '+91 98555 66778',
      email: 'kiran.reddy@example.com',
      occupation: 'Sales Manager',
      aadhaarNumber: '3456 7890 1243',
      aadhaarDocumentName: 'kiran-reddy-aadhaar.pdf',
    },
    address: { line1: '9, Aliganj', line2: '', city: 'Lucknow', state: 'Uttar Pradesh', pinCode: '226024' },
  },
  {
    admissionId: 'ADM-2026-1053',
    firstName: 'Anika',
    lastName: 'Desai',
    initials: 'AD',
    class: 'Class 8',
    section: 'A',
    academicSession: '2026-27',
    admissionDate: '2026-04-10',
    dob: '2013-12-07',
    gender: 'Female',
    bloodGroup: 'O-',
    nationality: 'India',
    aadhaarNumber: '4456 7890 1234',
    aadhaarDocumentName: 'anika-desai-aadhaar.pdf',
    whatsappNumber: '+91 98666 77889',
    status: 'Active',
    previousSchool: { name: 'St. Mary Convent School', board: 'ICSE', lastClassPercentage: '89%' },
    emergencyContacts: {
      primary: { name: 'Rohan Desai', relationship: 'Father', phone: '+91 98666 77889' },
      secondary: { name: '', relationship: '', phone: '' },
      trustedRelativePhone: '+91 98666 00033',
    },
    feeDetails: {
      admissionFeePaidDate: '2026-04-10',
      admissionFeeAmount: '15000',
      structureType: 'Annual',
      structureAmount: '85000',
      paymentStatus: 'Paid',
      outstandingDues: '0',
    },
    guardian: {
      relationship: 'Father',
      fullName: 'Rohan Desai',
      phone: '+91 98666 77889',
      email: 'rohan.desai@example.com',
      occupation: 'Marketing Manager',
      aadhaarNumber: '4567 8901 2354',
      aadhaarDocumentName: 'rohan-desai-aadhaar.pdf',
    },
    address: { line1: '61, Chinhat', line2: '', city: 'Lucknow', state: 'Uttar Pradesh', pinCode: '226028' },
  },
  {
    admissionId: 'ADM-2026-1054',
    firstName: 'Arjun',
    lastName: 'Malhotra',
    initials: 'AM',
    class: 'Class 9',
    section: 'A',
    academicSession: '2026-27',
    admissionDate: '2026-04-11',
    dob: '2012-04-15',
    gender: 'Male',
    bloodGroup: 'A+',
    nationality: 'India',
    aadhaarNumber: '5567 8901 2345',
    aadhaarDocumentName: 'arjun-malhotra-aadhaar.pdf',
    whatsappNumber: '+91 98777 88990',
    status: 'Active',
    previousSchool: { name: 'Bright Future School', board: 'CBSE', lastClassPercentage: '86%' },
    emergencyContacts: {
      primary: { name: 'Anil Malhotra', relationship: 'Father', phone: '+91 98777 88990' },
      secondary: { name: '', relationship: '', phone: '' },
      trustedRelativePhone: '+91 98777 00044',
    },
    feeDetails: {
      admissionFeePaidDate: '2026-04-11',
      admissionFeeAmount: '16000',
      structureType: 'Annual',
      structureAmount: '90000',
      paymentStatus: 'Paid',
      outstandingDues: '0',
    },
    guardian: {
      relationship: 'Father',
      fullName: 'Anil Malhotra',
      phone: '+91 98777 88990',
      email: 'anil.malhotra@example.com',
      occupation: 'Chartered Accountant',
      aadhaarNumber: '5678 9012 3465',
      aadhaarDocumentName: 'anil-malhotra-aadhaar.pdf',
    },
    address: { line1: '18, Mahanagar', line2: '', city: 'Lucknow', state: 'Uttar Pradesh', pinCode: '226006' },
  },
  {
    admissionId: 'ADM-2026-1055',
    firstName: 'Kiara',
    lastName: 'Bhatt',
    initials: 'KB',
    class: 'Class 9',
    section: 'A',
    academicSession: '2026-27',
    admissionDate: '2026-04-11',
    dob: '2012-09-21',
    gender: 'Female',
    bloodGroup: 'B+',
    nationality: 'India',
    aadhaarNumber: '6678 9012 3456',
    aadhaarDocumentName: 'kiara-bhatt-aadhaar.pdf',
    whatsappNumber: '+91 98888 99001',
    status: 'Active',
    previousSchool: { name: 'Sunrise Public School', board: 'ICSE', lastClassPercentage: '94%' },
    emergencyContacts: {
      primary: { name: 'Meera Bhatt', relationship: 'Mother', phone: '+91 98888 99001' },
      secondary: { name: '', relationship: '', phone: '' },
      trustedRelativePhone: '+91 98888 00055',
    },
    feeDetails: {
      admissionFeePaidDate: '2026-04-11',
      admissionFeeAmount: '16000',
      structureType: 'Annual',
      structureAmount: '90000',
      paymentStatus: 'Paid',
      outstandingDues: '0',
    },
    guardian: {
      relationship: 'Mother',
      fullName: 'Meera Bhatt',
      phone: '+91 98888 99001',
      email: 'meera.bhatt@example.com',
      occupation: 'Journalist',
      aadhaarNumber: '6789 0123 4576',
      aadhaarDocumentName: 'meera-bhatt-aadhaar.pdf',
    },
    address: { line1: '27, Rajajipuram', line2: '', city: 'Lucknow', state: 'Uttar Pradesh', pinCode: '226017' },
  },
  {
    admissionId: 'ADM-2026-1056',
    firstName: 'Advait',
    lastName: 'Rao',
    initials: 'AR',
    class: 'Class 9',
    section: 'A',
    academicSession: '2026-27',
    admissionDate: '2026-04-12',
    dob: '2012-06-09',
    gender: 'Male',
    bloodGroup: 'O+',
    nationality: 'India',
    aadhaarNumber: '7789 0123 4567',
    aadhaarDocumentName: 'advait-rao-aadhaar.pdf',
    whatsappNumber: '+91 98999 00112',
    status: 'Active',
    previousSchool: { name: 'Green Valley School', board: 'CBSE', lastClassPercentage: '82%' },
    emergencyContacts: {
      primary: { name: 'Prakash Rao', relationship: 'Father', phone: '+91 98999 00112' },
      secondary: { name: '', relationship: '', phone: '' },
      trustedRelativePhone: '+91 98999 00066',
    },
    feeDetails: {
      admissionFeePaidDate: '2026-04-12',
      admissionFeeAmount: '16000',
      structureType: 'Monthly',
      structureAmount: '7500',
      paymentStatus: 'Pending',
      outstandingDues: '7500',
    },
    guardian: {
      relationship: 'Father',
      fullName: 'Prakash Rao',
      phone: '+91 98999 00112',
      email: 'prakash.rao@example.com',
      occupation: 'Shop Owner',
      aadhaarNumber: '7890 1234 5687',
      aadhaarDocumentName: 'prakash-rao-aadhaar.pdf',
    },
    address: { line1: '40, Telibagh', line2: '', city: 'Lucknow', state: 'Uttar Pradesh', pinCode: '226002' },
  },
  {
    admissionId: 'ADM-2026-1057',
    firstName: 'Zara',
    lastName: 'Khan',
    initials: 'ZK',
    class: 'Class 9',
    section: 'A',
    academicSession: '2026-27',
    admissionDate: '2026-04-12',
    dob: '2012-11-27',
    gender: 'Female',
    bloodGroup: 'A-',
    nationality: 'India',
    aadhaarNumber: '8890 1234 5678',
    aadhaarDocumentName: 'zara-khan-aadhaar.pdf',
    whatsappNumber: '+91 99000 11223',
    status: 'Active',
    previousSchool: { name: 'Holy Cross School', board: 'ICSE', lastClassPercentage: '91%' },
    emergencyContacts: {
      primary: { name: 'Imran Khan', relationship: 'Father', phone: '+91 99000 11223' },
      secondary: { name: '', relationship: '', phone: '' },
      trustedRelativePhone: '+91 99000 00077',
    },
    feeDetails: {
      admissionFeePaidDate: '2026-04-12',
      admissionFeeAmount: '16000',
      structureType: 'Annual',
      structureAmount: '90000',
      paymentStatus: 'Paid',
      outstandingDues: '0',
    },
    guardian: {
      relationship: 'Father',
      fullName: 'Imran Khan',
      phone: '+91 99000 11223',
      email: 'imran.khan@example.com',
      occupation: 'IT Consultant',
      aadhaarNumber: '8901 2345 6798',
      aadhaarDocumentName: 'imran-khan-aadhaar.pdf',
    },
    address: { line1: '55, Jankipuram', line2: '', city: 'Lucknow', state: 'Uttar Pradesh', pinCode: '226021' },
  },
];

const BULK_FIRST_NAMES = [
  'Aryan', 'Diya', 'Kabir', 'Anaya', 'Rohan', 'Meera', 'Yash', 'Priya', 'Arnav', 'Tara',
  'Ishaan', 'Nisha', 'Dev', 'Kavya', 'Rudra', 'Sana', 'Manav', 'Riya', 'Aditya', 'Isha',
  'Vivek', 'Neha', 'Karan', 'Pooja', 'Siddharth', 'Anjali', 'Vikram', 'Simran', 'Rahul', 'Divya',
  'Nikhil', 'Sneha', 'Aman', 'Radhika', 'Sameer', 'Pallavi', 'Harsh', 'Swati', 'Gaurav', 'Ritika',
];
const BULK_LAST_NAMES = [
  'Sharma', 'Verma', 'Gupta', 'Singh', 'Kapoor', 'Mehta', 'Nair', 'Iyer', 'Reddy', 'Desai',
  'Malhotra', 'Bhatt', 'Rao', 'Khan', 'Joshi', 'Patel', 'Chauhan', 'Agarwal', 'Bose', 'Chatterjee',
  'Menon', 'Pillai', 'Trivedi', 'Saxena', 'Bhatia', 'Chopra', 'Dutta', 'Ghosh', 'Kulkarni', 'Naidu',
];

function buildBulkStudent({ seq, admissionNumber, firstName, lastName, className, section, gender }) {
  return {
    admissionId: `ADM-2026-${admissionNumber}`,
    firstName,
    lastName,
    initials: `${firstName[0]}${lastName[0]}`.toUpperCase(),
    class: className,
    section,
    academicSession: '2026-27',
    admissionDate: '2026-04-15',
    dob: '2013-01-01',
    gender,
    bloodGroup: 'O+',
    nationality: 'India',
    aadhaarNumber: `${1000 + seq} 0000 0000`,
    aadhaarDocumentName: `${firstName.toLowerCase()}-${lastName.toLowerCase()}-aadhaar.pdf`,
    whatsappNumber: '+91 90000 00000',
    status: 'Active',
    previousSchool: { name: 'City Public School', board: 'CBSE', lastClassPercentage: '85%' },
    emergencyContacts: {
      primary: { name: `Parent of ${firstName}`, relationship: 'Father', phone: '+91 90000 00000' },
      secondary: { name: '', relationship: '', phone: '' },
      trustedRelativePhone: '+91 90000 00001',
    },
    feeDetails: {
      admissionFeePaidDate: '2026-04-15',
      admissionFeeAmount: '15000',
      structureType: 'Annual',
      structureAmount: '85000',
      paymentStatus: 'Paid',
      outstandingDues: '0',
    },
    guardian: {
      relationship: 'Father',
      fullName: `Parent of ${firstName}`,
      phone: '+91 90000 00000',
      email: `${firstName.toLowerCase()}.guardian@example.com`,
      occupation: 'Professional',
      aadhaarNumber: `${2000 + seq} 0000 0000`,
      aadhaarDocumentName: `${firstName.toLowerCase()}-guardian-aadhaar.pdf`,
    },
    address: { line1: `${seq}, Model Colony`, line2: '', city: 'Lucknow', state: 'Uttar Pradesh', pinCode: '226001' },
  };
}

function generateBulkStudents(startSeq, count, className, section, admissionStart) {
  const students = [];
  for (let i = 0; i < count; i++) {
    const firstName = BULK_FIRST_NAMES[i % BULK_FIRST_NAMES.length];
    const lastName = BULK_LAST_NAMES[(i + Math.floor(i / BULK_FIRST_NAMES.length)) % BULK_LAST_NAMES.length];
    students.push(
      buildBulkStudent({
        seq: startSeq + i,
        admissionNumber: admissionStart + i,
        firstName,
        lastName,
        className,
        section,
        gender: i % 2 === 0 ? 'Male' : 'Female',
      })
    );
  }
  return students;
}

// Class 8-A: 42 generated (on top of the 8 hand-authored above = 50 total)
// Class 9-A: 24 generated (on top of the 4 hand-authored above = 28 total)
const BULK_CLASS_8A = generateBulkStudents(0, 42, 'Class 8', 'A', 1058);
const BULK_CLASS_9A = generateBulkStudents(42, 24, 'Class 9', 'A', 1200);

export const SEED_STUDENT_ROSTER = [...SEED_STUDENTS, ...BULK_CLASS_8A, ...BULK_CLASS_9A];
