// Same demo roster lib/teachers.js used to hold in an in-memory array —
// moved out so prisma/seed.js can import it the same way it already imports
// lib/studentSeedData.js. `loginAccess.password` here is the plaintext demo
// password seed.js hashes before writing it to Teacher.loginPasswordHash —
// nothing reads this field as-is.
export const SEED_TEACHERS = [
  {
    employeeId: 'TCH-2026-001',
    firstName: 'Rahul',
    middleName: '',
    lastName: 'Kumar',
    initials: 'RK',
    dob: '1988-05-14',
    gender: 'Male',
    bloodGroup: 'B+',
    phone: '+91 98765 43221',
    email: 'rahul.kumar@edumanage.com',
    aadhaarNumber: '1234 5678 9011',
    aadhaarDocumentName: 'rahul-kumar-aadhaar.pdf',
    maritalStatus: 'Married',
    nationality: 'Indian',
    panNumber: 'ABCPK1234F',
    isFresher: false,
    education: {
      tenthPercentage: '88%',
      twelfthPercentage: '91%',
      graduationDegree: 'M.Sc. Mathematics',
      graduationUniversity: 'University of Lucknow',
    },
    bankDetails: {
      accountHolderName: 'Rahul Kumar',
      bankName: 'State Bank of India',
      accountNumber: '30123456789',
      ifsc: 'SBIN0001234',
    },
    emergencyContact: { name: 'Sunil Kumar', phone: '+91 98765 12340', relationship: 'Parent' },
    joiningDate: '2019-06-01',
    relievingDate: '',
    qualification: 'M.Sc. Mathematics, B.Ed.',
    specialization: 'Mathematics',
    experience: '7 years',
    employmentType: 'Full Time',
    status: 'Active',
    designation: 'Mathematics Teacher',
    loginAccess: { enabled: true, email: 'rahul.kumar@edumanage.com', password: 'Teacher@123', accountStatus: 'Active' },
    address: { line1: '12, Vivek Vihar', line2: '', city: 'Lucknow', state: 'Uttar Pradesh', pinCode: '226010' },
    assignments: [
      { id: 'a1', academicSession: '2026-27', class: 'Class 8', section: 'A', status: 'Active' },
      { id: 'a2', academicSession: '2026-27', class: 'Class 9', section: 'A', status: 'Active' },
    ],
  },
  {
    employeeId: 'TCH-2026-002',
    firstName: 'Priya',
    middleName: '',
    lastName: 'Sharma',
    initials: 'PS',
    dob: '1990-09-22',
    gender: 'Female',
    bloodGroup: 'O+',
    phone: '+91 97654 32144',
    email: 'priya.sharma@edumanage.com',
    aadhaarNumber: '2345 6789 0122',
    aadhaarDocumentName: 'priya-sharma-aadhaar.pdf',
    maritalStatus: 'Single',
    nationality: 'Indian',
    panNumber: 'BCDPS2345G',
    isFresher: false,
    education: {
      tenthPercentage: '90%',
      twelfthPercentage: '87%',
      graduationDegree: 'M.A. English Literature',
      graduationUniversity: 'Delhi University',
    },
    bankDetails: {
      accountHolderName: 'Priya Sharma',
      bankName: 'HDFC Bank',
      accountNumber: '50123456780',
      ifsc: 'HDFC0004567',
    },
    emergencyContact: { name: 'Amit Sharma', phone: '+91 97654 12341', relationship: 'Sibling' },
    joiningDate: '2020-07-15',
    relievingDate: '',
    qualification: 'M.A. English Literature, B.Ed.',
    specialization: 'English',
    experience: '5 years',
    employmentType: 'Full Time',
    status: 'Active',
    designation: 'English Teacher',
    loginAccess: { enabled: true, email: 'priya.sharma@edumanage.com', password: 'Teacher@123', accountStatus: 'Active' },
    address: { line1: '48, Sector 12', line2: '', city: 'Noida', state: 'Uttar Pradesh', pinCode: '201301' },
    assignments: [{ id: 'a3', academicSession: '2026-27', class: 'Class 7', section: 'B', status: 'Active' }],
  },
  {
    employeeId: 'TCH-2026-003',
    firstName: 'Anil',
    middleName: '',
    lastName: 'Verma',
    initials: 'AV',
    dob: '1985-01-30',
    gender: 'Male',
    bloodGroup: 'A+',
    phone: '+91 99887 66551',
    email: 'anil.verma@edumanage.com',
    aadhaarNumber: '3456 7890 1233',
    aadhaarDocumentName: 'anil-verma-aadhaar.pdf',
    maritalStatus: 'Married',
    nationality: 'Indian',
    panNumber: 'CDEPV3456H',
    isFresher: false,
    education: {
      tenthPercentage: '85%',
      twelfthPercentage: '89%',
      graduationDegree: 'M.Sc. Physics',
      graduationUniversity: 'Chhatrapati Shahu Ji Maharaj University',
    },
    bankDetails: {
      accountHolderName: 'Anil Verma',
      bankName: 'Punjab National Bank',
      accountNumber: '01123456782',
      ifsc: 'PUNB0112300',
    },
    emergencyContact: { name: 'Reena Verma', phone: '+91 99887 12342', relationship: 'Spouse' },
    joiningDate: '2016-04-10',
    relievingDate: '',
    qualification: 'M.Sc. Physics, B.Ed.',
    specialization: 'Physics',
    experience: '10 years',
    employmentType: 'Full Time',
    status: 'Active',
    designation: 'Physics Teacher',
    loginAccess: { enabled: true, email: 'anil.verma@edumanage.com', password: 'Teacher@123', accountStatus: 'Active' },
    address: { line1: '15, MG Road', line2: '', city: 'Kanpur', state: 'Uttar Pradesh', pinCode: '208001' },
    assignments: [{ id: 'a4', academicSession: '2026-27', class: 'Class 8', section: 'B', status: 'Active' }],
  },
  {
    employeeId: 'TCH-2026-004',
    firstName: 'Sunita',
    middleName: '',
    lastName: 'Gupta',
    initials: 'SG',
    dob: '1992-03-18',
    gender: 'Female',
    bloodGroup: 'AB+',
    phone: '+91 90000 11224',
    email: 'sunita.gupta@edumanage.com',
    aadhaarNumber: '4567 8901 2344',
    aadhaarDocumentName: 'sunita-gupta-aadhaar.pdf',
    maritalStatus: 'Married',
    nationality: 'Indian',
    panNumber: 'DEFPG4567I',
    isFresher: false,
    education: {
      tenthPercentage: '78%',
      twelfthPercentage: '80%',
      graduationDegree: 'B.A. History',
      graduationUniversity: 'Dr. Bhimrao Ambedkar University',
    },
    bankDetails: {
      accountHolderName: 'Sunita Gupta',
      bankName: 'Bank of Baroda',
      accountNumber: '20123456783',
      ifsc: 'BARB0AGRAXX',
    },
    emergencyContact: { name: 'Rakesh Gupta', phone: '+91 90000 12343', relationship: 'Spouse' },
    joiningDate: '2021-01-05',
    relievingDate: '',
    qualification: 'B.A., B.Ed.',
    specialization: 'Social Studies',
    experience: '4 years',
    employmentType: 'Part Time',
    status: 'Active',
    designation: 'Social Studies Teacher',
    loginAccess: { enabled: false, email: '', password: '', accountStatus: 'Suspended' },
    address: { line1: '9, Civil Lines', line2: '', city: 'Agra', state: 'Uttar Pradesh', pinCode: '282002' },
    assignments: [{ id: 'a5', academicSession: '2026-27', class: 'Class 6', section: 'C', status: 'Active' }],
  },
  {
    employeeId: 'TCH-2026-005',
    firstName: 'Deepak',
    middleName: '',
    lastName: 'Mehta',
    initials: 'DM',
    dob: '1983-11-02',
    gender: 'Male',
    bloodGroup: 'O-',
    phone: '+91 98123 45671',
    email: 'deepak.mehta@edumanage.com',
    aadhaarNumber: '5678 9012 3455',
    aadhaarDocumentName: 'deepak-mehta-aadhaar.pdf',
    maritalStatus: 'Married',
    nationality: 'Indian',
    panNumber: 'EFGPM5678J',
    isFresher: false,
    education: {
      tenthPercentage: '82%',
      twelfthPercentage: '86%',
      graduationDegree: 'M.Sc. Chemistry',
      graduationUniversity: 'Chaudhary Charan Singh University',
    },
    bankDetails: {
      accountHolderName: 'Deepak Mehta',
      bankName: 'ICICI Bank',
      accountNumber: '60123456784',
      ifsc: 'ICIC0006789',
    },
    emergencyContact: { name: 'Meena Mehta', phone: '+91 98123 12344', relationship: 'Spouse' },
    joiningDate: '2014-06-20',
    relievingDate: '2025-03-31',
    qualification: 'M.Sc. Chemistry, B.Ed.',
    specialization: 'Chemistry',
    experience: '12 years',
    employmentType: 'Full Time',
    status: 'Inactive',
    designation: 'Chemistry Teacher',
    loginAccess: { enabled: true, email: 'deepak.mehta@edumanage.com', password: 'Teacher@123', accountStatus: 'Suspended' },
    address: { line1: '77, Model Town', line2: '', city: 'Meerut', state: 'Uttar Pradesh', pinCode: '250001' },
    assignments: [],
  },
  {
    employeeId: 'TCH-2026-006',
    firstName: 'Rekha',
    middleName: '',
    lastName: 'Kapoor',
    initials: 'RK',
    dob: '1995-07-09',
    gender: 'Female',
    bloodGroup: 'B-',
    phone: '+91 97654 32110',
    email: 'rekha.kapoor@edumanage.com',
    aadhaarNumber: '6789 0123 4566',
    aadhaarDocumentName: 'rekha-kapoor-aadhaar.pdf',
    maritalStatus: 'Single',
    nationality: 'Indian',
    panNumber: 'FGHPK6789K',
    isFresher: true,
    education: {
      tenthPercentage: '75%',
      twelfthPercentage: '79%',
      graduationDegree: 'B.P.Ed.',
      graduationUniversity: 'Lakshmibai National Institute of Physical Education',
    },
    bankDetails: {
      accountHolderName: 'Rekha Kapoor',
      bankName: 'Axis Bank',
      accountNumber: '91123456785',
      ifsc: 'UTIB0001122',
    },
    emergencyContact: { name: 'Vinod Kapoor', phone: '+91 97654 12345', relationship: 'Parent' },
    joiningDate: '2023-08-01',
    relievingDate: '',
    qualification: 'B.P.Ed.',
    specialization: 'Physical Education',
    experience: '2 years',
    employmentType: 'Contract',
    status: 'Active',
    designation: 'Physical Education Teacher',
    loginAccess: { enabled: true, email: 'rekha.kapoor@edumanage.com', password: 'Teacher@123', accountStatus: 'Active' },
    address: { line1: '3, Shastri Nagar', line2: '', city: 'Ghaziabad', state: 'Uttar Pradesh', pinCode: '201001' },
    assignments: [{ id: 'a6', academicSession: '2026-27', class: 'Class 5', section: 'A', status: 'Active' }],
  },
];
